### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo2#63]
Writing the getting started tutorials a few things emerged that may be easy to implement:

 - [x] Providing some sort of iterator in the archipelago class as to allow ranged based for loops
 - [x] Changing the meaning of the seed in the archipelago constructor so that it becomes a generator for seeds of the various populations in the islands. This would avoid identical pops to be constructed in the different islands (#74)
 - [x] Provide a pagmo.hpp header, and maybe the algorithms.hpp and problems.hpp headers.
 - [x] Make some sort of minimal unified log for NLOPT algorithms.
 - [x] Fix the behaviour of population.push_back so that its checks are consistent with population.set_xf. And avoid crashes 
 - [x] The kwarg in the archipelago constructor could be pop_size and not size (#74)
 - [x] The line  ```res = [isl.get_population().champion_f for isl in archi]``` is a quite common pattern and a dedicated method should maybe be added to the archi ```get_champions```? (#75)

**Comment by bluescarni** [comment]
Closed with #75.
